# coding=utf-8
from public.selenium_page import SeleniumPage
from qiqiao_page.mobile_page.business_components.bottomMenu_component import BottomMenuComponent
from qiqiao_page.mobile_page.business_components.customizePage_component import CustomizePageComponent
from qiqiao_page.mobile_page.business_components.form_component import FormComponent
from qiqiao_page.mobile_page.business_components.list_component import ListComponent
from qiqiao_page.mobile_page.business_components.navigation_component import NavigationComponent
from qiqiao_page.mobile_page.business_components.pic_component import PicComponent
from qiqiao_page.mobile_page.business_components.rankingList_component import RankingListComponent
from qiqiao_page.mobile_page.business_components.report_component import ReportComponent
from qiqiao_page.mobile_page.business_components.splitLine_component import SplitLineComponent
from qiqiao_page.mobile_page.business_components.statistics_component import StatisticsComponent
from qiqiao_page.mobile_page.business_components.summaryList_component import SummaryListComponent
from qiqiao_page.mobile_page.business_components.text_component import TextComponent
from qiqiao_page.mobile_page.business_components.treeList_component import TreeListComponent


class BusinessModelldPage(BottomMenuComponent,CustomizePageComponent,FormComponent,ListComponent,NavigationComponent,PicComponent,RankingListComponent,ReportComponent,SplitLineComponent,StatisticsComponent,SummaryListComponent,TextComponent,TreeListComponent):


    pass