# coding=utf-8
from public.selenium_page import SeleniumPage
from qiqiao_page.mobile_page.business_components.mb_bottomMenu_component import BottomMenuComponent
from qiqiao_page.mobile_page.business_components.mb_customizePage_component import CustomizePageComponent
from qiqiao_page.mobile_page.business_components.mb_form_component import FormComponent
from qiqiao_page.mobile_page.business_components.mb_list_component import ListComponent
from qiqiao_page.mobile_page.business_components.mb_navigation_component import NavigationComponent
from qiqiao_page.mobile_page.business_components.mb_pic_component import PicComponent
from qiqiao_page.mobile_page.business_components.mb_rankingList_component import RankingListComponent
from qiqiao_page.mobile_page.business_components.mb_report_component import ReportComponent
from qiqiao_page.mobile_page.business_components.mb_splitLine_component import SplitLineComponent
from qiqiao_page.mobile_page.business_components.mb_statistics_component import StatisticsComponent
from qiqiao_page.mobile_page.business_components.mb_summaryList_component import SummaryListComponent
from qiqiao_page.mobile_page.business_components.mb_text_component import TextComponent
from qiqiao_page.mobile_page.business_components.mb_treeList_component import TreeListComponent


class MbBusinessPage(BottomMenuComponent,CustomizePageComponent,FormComponent,ListComponent,NavigationComponent,PicComponent,RankingListComponent,ReportComponent,SplitLineComponent,StatisticsComponent,SummaryListComponent,TextComponent,TreeListComponent):


    pass