# coding=utf-8
from public.selenium_page import SeleniumPage
from qiqiao_page.mobile_page.business_components.mb_bottomMenu_component import MbBottomMenuComponent
from qiqiao_page.mobile_page.business_components.mb_customizePage_component import MbCustomizePageComponent
from qiqiao_page.mobile_page.business_components.mb_form_component import MbFormComponent
from qiqiao_page.mobile_page.business_components.mb_list_component import MbListComponent
from qiqiao_page.mobile_page.business_components.mb_navigation_component import MbNavigationComponent
from qiqiao_page.mobile_page.business_components.mb_pic_component import MbPicComponent
from qiqiao_page.mobile_page.business_components.mb_rankingList_component import MbRankingListComponent
from qiqiao_page.mobile_page.business_components.mb_report_component import MbReportComponent
from qiqiao_page.mobile_page.business_components.mb_splitLine_component import MbSplitLineComponent
from qiqiao_page.mobile_page.business_components.mb_statistics_component import MbStatisticsComponent
from qiqiao_page.mobile_page.business_components.mb_summaryList_component import MbSummaryListComponent
from qiqiao_page.mobile_page.business_components.mb_text_component import MbTextComponent
from qiqiao_page.mobile_page.business_components.mb_treeList_component import MbTreeListComponent


class MbBusinessPage(MbBottomMenuComponent,MbCustomizePageComponent,MbFormComponent,MbListComponent,MbNavigationComponent,MbPicComponent,MbRankingListComponent,MbReportComponent,MbSplitLineComponent,MbStatisticsComponent,MbSummaryListComponent,MbTextComponent,MbTreeListComponent):


    pass