# coding=utf-8
import time
import unittest

from public.driver import Driver
from qiqiao_page.pc_page.applicationList_page import ApplicationListPage
from qiqiao_page.pc_page.business_page import BusinessPage
from qiqiao_page.pc_page.form_page import FormPage
from qiqiao_page.pc_page.login_page import LoginPage
from qiqiao_page.pc_page.portal_page import PortalPage
from qiqiao_page.pc_page.process_page import ProcessPage


class ProcessAppTest_001(unittest.TestCase):
    '''流程应用检查'''


    def pcLogin(self,account,password):
        '''登录pc端'''
        self.driver = Driver().pcdriver()
        self.driver.maximize_window()
        loginpage = LoginPage(self.driver)
        loginpage.user_login('https://qy.do1.com.cn/qiqiao/runtime', account, password)
        time.sleep(5)


    def test_01( self ):
        '''处理人设置测试流程--用户'''
        self.pcLogin("diaohuiyun@A1","qiqiao123")
        portalPage = PortalPage(self.driver)
        #打开“发起流程列表”
        portalPage.PortalPage_Click_HeaderMenu('流程')
        time.sleep(3)
        processPage = ProcessPage(self.driver)
        processPage.ProcessPage_click_process_icon("处理人设置测试流程")
        formPage = FormPage(self.driver)
        formPage.Text_Sendkeys("单行文本","用户")
        formPage.Form_Switch_Tab("人员部门类组件")
        formPage.User_MonomialUser_Sendkeys("人员单选","张月娟")
        formPage.User_MultiUser_Sendkeys("人员多选",["周子贤","周润泽"])
        formPage.Dept_MonomialDept_Sendkeys("部门单选","产品研发二部",index=1)
        formPage.Dept_MultiDept_Sendkeys("部门多选",{"产品研发二部":1,"产品研发一部":1})
        formPage.Form_Button_Click("办理")
        self.assertEqual(formPage.Form_Get_ProcessManagers(),["吴健伦"],msg="固定用户人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功', formPage.Public_GetAlertMessage(), msg="第1个人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wujianlun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['周润泽', '张月娟', '周子贤'],msg="表单人员字段人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="表单人员字段人工任务办理失败")
        self.driver.quit()
        self.pcLogin("zhangyuejuan@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_Select_ProcessManager(["罗琳月"])
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="由上个任务的办理者任意指定人工任务办理失败")
        self.driver.quit()
        self.pcLogin("luolinyue@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['罗琳月'],msg="上个任务办理者的办理者人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="上个任务办理者的办理者人工任务办理失败")
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),["吴健伦"],msg="上个任务办理者的部门主管人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="上个任务办理者的部门主管人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wujianlun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_Select_ProcessManager(["刁惠云"])
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="任意指定人工任务办理失败")
        self.driver.quit()
        self.pcLogin("diaohuiyun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),["吴健伦"],msg="上个任务办理者的上级部门主管人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="上个任务办理者的上级部门主管人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wujianlun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),["吴健伦"],msg="与指定节点办理者相关人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="与指定节点办理者相关人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wujianlun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['刁惠云'],msg="流程发起人人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="流程发起人人工任务办理失败")
        self.driver.quit()
        self.pcLogin("diaohuiyun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['王栋一'],msg="流程发起人的部门主管人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="流程发起人的部门主管人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wangdongyi@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),["吴健伦"],msg="流程发起人的上级部门主管人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="流程发起人的上级部门主管人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wujianlun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['王浩'],msg="人工任务3人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="人工任务3人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wanghao@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="人工任务3办理失败")


    def test_02( self ):
        '''处理人设置测试流程--标签'''
        self.pcLogin("wujianlun@A1","qiqiao123")
        portalPage = PortalPage(self.driver)
        #打开“发起流程列表”
        portalPage.PortalPage_Click_HeaderMenu('流程')
        time.sleep(3)
        processPage = ProcessPage(self.driver)
        processPage.ProcessPage_click_process_icon("处理人设置测试流程")
        formPage = FormPage(self.driver)
        formPage.Text_Sendkeys("单行文本","标签")
        formPage.Form_Switch_Tab("人员部门类组件")
        formPage.User_MonomialUser_Sendkeys("人员单选","张月娟")
        formPage.User_MultiUser_Sendkeys("人员多选",["周子贤","周润泽"])
        formPage.Dept_MonomialDept_Sendkeys("部门单选","产品研发二部",index=1)
        formPage.Dept_MultiDept_Sendkeys("部门多选",{"产品研发二部":1,"产品研发一部":1})
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['李旭明', '朱浪锋', '罗琳月', '罗静文', '钟振东', '吴健伦', '黎杨辉', '王浩', '程林'],msg="多用户标签人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功', formPage.Public_GetAlertMessage(), msg="多用户标签人工任务办理失败")
        self.driver.quit()
        self.pcLogin("luolinyue@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['周翠', '周煊', '周婉芳', '周士钦', '周舂华', '周楚桥', '周丹晴', '周明梅', '周佩意', '周新爱', '周润泽', '周一诺', '周铭', '周兴', '周君燕', '周臻妮', '周政', '周永继', '周潇', '周敏敏', '周俞臻', '周煊妮', '周俐臻', '周敏', '周唯臻', '周金铭', '周新月', '周金芸', '周月清', '周美臻', '周虎', '周子贤', '周英姿', '王栋一', '周泉君', '周舒臻', '李嘉诚', '王浩', '周佩臻', '周臻', '周才渊', '周煊昊', '周到钧', '周于钦', '周柔臻', '赵婧文'],msg="部门加用户标签人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="部门加用户标签人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wanghao@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['梁华', '邓基富', '刁惠云', '张鹏飞', '郑云龙', '刘海涛', '王栋一', '庄荣填', '李嘉诚', '范宇民'],msg="多部门标签人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="多部门标签人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wangdongyi@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="人工任务3办理失败")
        self.driver.quit()
        self.pcLogin("wanghao@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="人工任务3办理失败")



    def test_03( self ):
        '''处理人设置测试流程--部门'''
        self.pcLogin("wujianlun@A1","qiqiao123")
        portalPage = PortalPage(self.driver)
        #打开“发起流程列表”
        portalPage.PortalPage_Click_HeaderMenu('流程')
        time.sleep(3)
        processPage = ProcessPage(self.driver)
        processPage.ProcessPage_click_process_icon("处理人设置测试流程")
        formPage = FormPage(self.driver)
        formPage.Text_Sendkeys("单行文本","部门")
        formPage.Form_Switch_Tab("人员部门类组件")
        formPage.User_MonomialUser_Sendkeys("人员单选","张月娟")
        formPage.User_MultiUser_Sendkeys("人员多选",["周子贤","周润泽"])
        formPage.Dept_MonomialDept_Sendkeys("部门单选","研发二组",index=1)
        formPage.Dept_MultiDept_Sendkeys("部门多选",{"研发二组":1,"产品规划组":1})
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['吴健伦'],msg="固定部门人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功', formPage.Public_GetAlertMessage(), msg="固定部门人工任务办理失败")

        self.driver.quit()
        self.pcLogin("wujianlun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),[ '梁华', '李旭明', '朱浪锋', '罗琳月', '武探星', '林镇伟', '张焕珽', '吴茵婷', '罗静文', '钟振东', '黄蕴彤', '邓基富', '刁惠云', '曾嘉凌', '张鹏飞', '吴健伦', '郑云龙', '刘海涛', '王栋一', '庄荣填', '李嘉诚', '黎杨辉', '王浩', '程林', '范宇民'],msg="表单部门字段人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="表单部门字段人工任务办理失败")
        self.driver.quit()
        self.pcLogin("diaohuiyun@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['梁华', '邓基富', '刁惠云', '张鹏飞', '郑云龙', '刘海涛', '王栋一', '庄荣填', '李嘉诚', '范宇民'],msg="与上个任务办理人所在部门相关人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="与上个任务办理人所在部门相关人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wangdongyi@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),[ '李旭明', '朱浪锋', '罗琳月', '武探星', '林镇伟', '张焕珽', '吴茵婷', '罗静文', '钟振东', '黄蕴彤', '曾嘉凌', '吴健伦', '黎杨辉', '王浩', '程林'],msg="流程发起人的所在部门相关人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="流程发起人的所在部门相关人工任务办理失败")
        self.driver.quit()
        self.pcLogin("luolinyue@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="人工任务3办理失败")
        self.driver.quit()
        self.pcLogin("wanghao@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="人工任务3办理失败")


    def test_04( self ):
        '''处理人设置测试流程--脚本'''
        self.pcLogin("wujianlun@A1","qiqiao123")
        portalPage = PortalPage(self.driver)
        #打开“发起流程列表”
        portalPage.PortalPage_Click_HeaderMenu('流程')
        time.sleep(3)
        processPage = ProcessPage(self.driver)
        processPage.ProcessPage_click_process_icon("处理人设置测试流程")
        formPage = FormPage(self.driver)
        formPage.Text_Sendkeys("单行文本","脚本")
        formPage.Form_Switch_Tab("人员部门类组件")
        formPage.User_MonomialUser_Sendkeys("人员单选","张月娟")
        formPage.User_MultiUser_Sendkeys("人员多选",["周子贤","周润泽"])
        formPage.Dept_MonomialDept_Sendkeys("部门单选","研发二组",index=1)
        formPage.Dept_MultiDept_Sendkeys("部门多选",{"研发二组":1,"产品规划组":1})
        formPage.Form_Button_Click("办理")
        print(formPage.Form_Get_ProcessManagers())
        self.assertEqual(formPage.Form_Get_ProcessManagers(),['王栋一'],msg="脚本人工任务办理者错误")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功', formPage.Public_GetAlertMessage(), msg="脚本人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wangdongyi@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="脚本人工任务办理失败")
        self.driver.quit()
        self.pcLogin("wanghao@A1","qiqiao123")
        formPage = FormPage(self.driver)
        processPage = ProcessPage(self.driver)
        portalPage = PortalPage(self.driver)
        portalPage.PortalPage_Click_HeaderMenu('流程')
        processPage.ProcessPage_click_process_menu("我的待办")
        processPage.ProcessPage_click_process_record(1)
        formPage.Form_Button_Click("办理")
        formPage.Form_ProcessHandle_Pop_QuerenButton_Click()
        self.assertIn('成功',formPage.Public_GetAlertMessage(),msg="人工任务3办理失败")



